# Generated by Django 5.1.7 on 2026-08-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usac", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="examination_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pre_employment", "Pre-Employment Medical Examination"),
                    ("periodic", "Periodic Medical Examination"),
                    ("return_to_work", "Return-to-Work Examination"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="examination_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pre_employment", "Pre-Employment Medical Examination"),
                    ("periodic", "Periodic Medical Examination"),
                    ("return_to_work", "Return-to-Work Examination"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
