# Generated by Django 5.1.7 on 2025-04-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_rop', '0003_predictionlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='single_rop/'),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
