# Generated by Django 5.1.7 on 2025-04-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_rop', '0004_predictionlog_image_predictionlog_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='corrected_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
