# Generated by Django 5.1.7 on 2025-04-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_rop', '0005_predictionlog_corrected_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='stage_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='stage_probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
