# Generated by Django 5.1.7 on 2025-04-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_rop', '0006_predictionlog_stage_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionlog',
            name='stage_probability',
            field=models.FloatField(),
        ),
    ]
