# Generated by Django 5.1.7 on 2025-04-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_rop', '0008_alter_predictionlog_stage_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionlog',
            name='stage_probability',
            field=models.FloatField(blank=True),
        ),
    ]
