# Generated by Django 5.1.7 on 2025-04-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_rop', '0010_alter_predictionlog_stage_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='stage_corrected_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='predictionlog',
            name='stage_probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
