# Generated by Django 5.1.7 on 2025-04-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_rop', '0011_predictionlog_stage_corrected_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionlog',
            name='stage_probability',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
