# Generated by Django 5.1.7 on 2025-04-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_rop', '0012_alter_predictionlog_stage_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='classification_status',
            field=models.IntegerField(default=1),
        ),
    ]
