# Generated by Django 5.1.7 on 2025-05-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_rop', '0013_predictionlog_classification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='segmented_image',
            field=models.ImageField(blank=True, null=True, upload_to='segmented/'),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='segmented_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
