# Generated by Django 5.1.7 on 2025-09-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_rop', '0014_predictionlog_segmented_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='zone_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='zone_corrected_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='zone_probability',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
