# Generated by Django 5.1.7 on 2025-09-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_rop', '0015_predictionlog_zone_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='final_decision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
