# Generated by Django 5.1.7 on 2026-07-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_rop', '0016_predictionlog_final_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='doctor_assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='doctor_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
