# Generated by Django 5.1.7 on 2025-06-29 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('children_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('military_service_status', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_exemption_reason', models.TextField(blank=True, null=True)),
                ('current_job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('current_job_duties', models.TextField(blank=True, null=True)),
                ('previous_job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_job_duties', models.TextField(blank=True, null=True)),
                ('job_change_reason', models.TextField(blank=True, null=True)),
                ('physical_hazards', models.TextField(blank=True, help_text='e.g., Noise, Vibration, Radiation', null=True)),
                ('chemical_hazards', models.TextField(blank=True, help_text='e.g., Dust, Solvents, Acids', null=True)),
                ('biological_hazards', models.TextField(blank=True, help_text='e.g., Viruses, Bacteria, Bites', null=True)),
                ('ergonomic_hazards', models.TextField(blank=True, help_text='e.g., Prolonged standing, Repetitive tasks', null=True)),
                ('psychological_hazards', models.TextField(blank=True, help_text='e.g., Shift work, Stress', null=True)),
                ('has_disease_history', models.BooleanField(default=False)),
                ('disease_history_details', models.TextField(blank=True, null=True)),
                ('does_symptoms_change_at_work', models.BooleanField(default=False)),
                ('do_colleagues_have_similar_symptoms', models.BooleanField(default=False)),
                ('does_symptoms_change_on_holidays', models.BooleanField(default=False)),
                ('has_allergies', models.BooleanField(default=False)),
                ('allergy_details', models.TextField(blank=True, null=True)),
                ('has_hospitalization_history', models.BooleanField(default=False)),
                ('hospitalization_reason', models.TextField(blank=True, null=True)),
                ('has_surgery_history', models.BooleanField(default=False)),
                ('surgery_details', models.TextField(blank=True, null=True)),
                ('has_family_cancer_or_chronic_disease', models.BooleanField(default=False)),
                ('family_disease_details', models.TextField(blank=True, null=True)),
                ('is_on_medication', models.BooleanField(default=False)),
                ('medication_details', models.TextField(blank=True, null=True)),
                ('is_currently_smoking', models.BooleanField(default=False)),
                ('smoking_details', models.CharField(blank=True, max_length=100, null=True)),
                ('has_past_smoking_history', models.BooleanField(default=False)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('has_occupational_accident_history', models.BooleanField(default=False)),
                ('accident_details', models.TextField(blank=True, null=True)),
                ('general_exam_notes', models.TextField(blank=True, null=True)),
                ('eye_exam_notes', models.TextField(blank=True, null=True)),
                ('skin_hair_nails_exam_notes', models.TextField(blank=True, null=True)),
                ('ent_mouth_exam_notes', models.TextField(blank=True, null=True)),
                ('head_neck_exam_notes', models.TextField(blank=True, null=True)),
                ('lung_exam_notes', models.TextField(blank=True, null=True)),
                ('cardiovascular_exam_notes', models.TextField(blank=True, null=True)),
                ('abdomen_pelvis_exam_notes', models.TextField(blank=True, null=True)),
                ('urinary_system_exam_notes', models.TextField(blank=True, null=True)),
                ('musculoskeletal_exam_notes', models.TextField(blank=True, null=True)),
                ('nervous_system_exam_notes', models.TextField(blank=True, null=True)),
                ('mental_health_exam_notes', models.TextField(blank=True, null=True)),
                ('lab_test_file_1', models.FileField(blank=True, null=True, upload_to='lab_tests/')),
                ('lab_test_file_2', models.FileField(blank=True, null=True, upload_to='lab_tests/')),
                ('lab_test_file_3', models.FileField(blank=True, null=True, upload_to='lab_tests/')),
                ('spirometry_fvc', models.CharField(blank=True, max_length=50, null=True)),
                ('spirometry_fev1', models.CharField(blank=True, max_length=50, null=True)),
                ('spirometry_fev1_fvc_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('spirometry_interpretation', models.TextField(blank=True, null=True)),
                ('ecg_findings', models.TextField(blank=True, null=True)),
                ('chest_xray_findings', models.TextField(blank=True, null=True)),
                ('referral_notes', models.TextField(blank=True, null=True)),
                ('llm_advice', models.TextField(blank=True, help_text='Advice generated by the LLM.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
