# Generated by Django 5.1.7 on 2025-07-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthprofile',
            old_name='lab_test_file_1',
            new_name='lab_test_files',
        ),
        migrations.RenameField(
            model_name='healthprofile',
            old_name='job_change_reason',
            new_name='work_address',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='biological_hazards',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='chemical_hazards',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='ergonomic_hazards',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='lab_test_file_2',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='lab_test_file_3',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='physical_hazards',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='previous_job_duties',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='previous_job_title',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='psychological_hazards',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='referral_notes',
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='current_job_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='exam_blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='فشار خون (mmHg)'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ معاینه'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='exam_height',
            field=models.FloatField(blank=True, null=True, verbose_name='قد (Cm)'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='exam_pulse_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد نبض (دقیقه)'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='exam_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='وزن (Kg)'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'مرد'), ('Female', 'زن')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='has_absence_over_3_days',
            field=models.BooleanField(default=False, verbose_name='سابقه غیبت بیش از ۳ روز'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='has_medical_commission_referral',
            field=models.BooleanField(default=False, verbose_name='سابقه معرفی به کمیسیون پزشکی'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_biological_bacteria',
            field=models.BooleanField(default=False, verbose_name='باکتری'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_biological_bites',
            field=models.BooleanField(default=False, verbose_name='گزش'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_biological_other',
            field=models.TextField(blank=True, null=True, verbose_name='سایر موارد بیولوژیک'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_biological_parasite',
            field=models.BooleanField(default=False, verbose_name='انگل'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_biological_virus',
            field=models.BooleanField(default=False, verbose_name='ویروس'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_chemical_acids_bases',
            field=models.BooleanField(default=False, verbose_name='اسید و بازها'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_chemical_dust',
            field=models.BooleanField(default=False, verbose_name='گرد و غبار'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_chemical_gases',
            field=models.BooleanField(default=False, verbose_name='گازها'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_chemical_metal_fumes',
            field=models.BooleanField(default=False, verbose_name='دمه فلزات'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_chemical_other',
            field=models.TextField(blank=True, null=True, verbose_name='سایر موارد شیمیایی'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_chemical_pesticides',
            field=models.BooleanField(default=False, verbose_name='آفت کش ها'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_chemical_solvents',
            field=models.BooleanField(default=False, verbose_name='حلال ها'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_ergonomic_heavy_lifting',
            field=models.BooleanField(default=False, verbose_name='حمل بار سنگین'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_ergonomic_other',
            field=models.TextField(blank=True, null=True, verbose_name='سایر موارد ارگونومی'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_ergonomic_poor_posture',
            field=models.BooleanField(default=False, verbose_name='وضعیت نامناسب بدن'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_ergonomic_prolonged_sitting_standing',
            field=models.BooleanField(default=False, verbose_name='ایستادن یا نشستن طولانی'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_ergonomic_repetitive_work',
            field=models.BooleanField(default=False, verbose_name='کار تکراری'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_physical_heat_stress',
            field=models.BooleanField(default=False, verbose_name='استرس حرارتی'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_physical_ionizing_radiation',
            field=models.BooleanField(default=False, verbose_name='اشعه یونیزان'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_physical_noise',
            field=models.BooleanField(default=False, verbose_name='سر و صدا'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_physical_non_ionizing_radiation',
            field=models.BooleanField(default=False, verbose_name='اشعه غیر یونیزان'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_physical_other',
            field=models.TextField(blank=True, null=True, verbose_name='سایر موارد فیزیکی'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_physical_vibration',
            field=models.BooleanField(default=False, verbose_name='ارتعاش'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_psychological_other',
            field=models.TextField(blank=True, null=True, verbose_name='سایر موارد روانی'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_psychological_shift_work',
            field=models.BooleanField(default=False, verbose_name='نوبت کاری'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='hazard_psychological_stressors',
            field=models.BooleanField(default=False, verbose_name='استرسورهای شغلی'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='lab_cbc_rbc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='lab_cbc_wbc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='lab_fbs',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='lab_ua_prot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='lives_near_industrial_center',
            field=models.BooleanField(default=False, verbose_name='منزل در مجاورت مرکز صنعتی'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='medical_recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='توصیه های پزشکی لازم'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='military_service_rank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='opinion_fit',
            field=models.BooleanField(default=False, verbose_name='بلامانع'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='opinion_fit_conditions_details',
            field=models.TextField(blank=True, null=True, verbose_name='شرح شروط'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='opinion_fit_with_conditions',
            field=models.BooleanField(default=False, verbose_name='مشروط'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='opinion_unfit',
            field=models.BooleanField(default=False, verbose_name='عدم صلاحیت'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='opinion_unfit_reason',
            field=models.TextField(blank=True, null=True, verbose_name='علت عدم صلاحیت'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='other_paraclinical_notes',
            field=models.TextField(blank=True, null=True, verbose_name='نتایج رادیوگرافی، سونوگرافی...'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='spirometry_fef_25_75',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FEF 25-75%'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='spirometry_pef',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PEF'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='sym_gen_chronic_fatigue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='sym_gen_loss_of_appetite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='sym_gen_weight_loss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PreviousJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سمت')),
                ('duties', models.TextField(blank=True, null=True, verbose_name='وظیفه محوله')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('reason_for_leaving', models.TextField(blank=True, null=True, verbose_name='علت تغییر شغل')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_jobs', to='test_analysis.healthprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ ارجاع')),
                ('reason', models.TextField(verbose_name='علت ارجاع')),
                ('specialty', models.CharField(max_length=255, verbose_name='نوع تخصص')),
                ('result', models.TextField(verbose_name='نتیجه ارجاع')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='test_analysis.healthprofile')),
            ],
        ),
    ]
