# Generated by Django 5.1.7 on 2025-07-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_analysis', '0002_rename_lab_test_file_1_healthprofile_lab_test_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سن (age)'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='bmi',
            field=models.FloatField(blank=True, null=True, verbose_name='شاخص توده بدنی (BMI)'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='cigs_per_day',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد سیگار در روز (cigsPerDay)'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='exam_diastolic_bp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='فشار خون دیاستولیک (diaBP)'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='exam_systolic_bp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='فشار خون سیستولیک (sysBP)'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='has_diabetes',
            field=models.BooleanField(default=False, verbose_name='آیا سابقه دیابت دارید؟ (diabetes)'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='on_bp_meds',
            field=models.BooleanField(default=False, verbose_name='آیا داروی فشار خون مصرف می\u200cکنید؟ (BPMeds)'),
        ),
    ]
