# Generated by Django 5.1.7 on 2025-07-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_analysis', '0003_healthprofile_age_healthprofile_bmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='province_of_residence',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='استان محل زندگی'),
        ),
    ]
