# Generated by Django 5.1.7 on 2025-07-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_analysis', '0004_healthprofile_province_of_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='lab_glucose',
            field=models.FloatField(blank=True, null=True, verbose_name='Glucose (mg/dL)'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='lab_total_cholesterol',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Cholesterol (mg/dL)'),
        ),
    ]
