# Generated by Django 5.1.7 on 2025-08-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_analysis', '0005_healthprofile_lab_glucose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='chosen_ai_model',
            field=models.CharField(choices=[('gpt-4o-mini', 'OpenAI (GPT-4o Mini)'), ('llama3.2', 'Local Model (Llama 3.2)')], default='gpt-4o-mini', help_text='The AI model selected by the user for generating the report.', max_length=50, verbose_name='Selected AI Model'),
        ),
    ]
