# Generated by Django 5.1.7 on 2025-08-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_analysis', '0006_healthprofile_chosen_ai_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthprofile',
            name='chosen_ai_model',
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='model_used_for_advice',
            field=models.CharField(blank=True, choices=[('cloud_gpt', 'GPT-4o-mini (Cloud)'), ('local_llama', 'Llama 3.2 (Local)')], default='cloud_gpt', help_text='The AI model used to generate the last report.', max_length=20),
        ),
    ]
