# Generated by Django 5.1.7 on 2025-08-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_analysis', '0007_remove_healthprofile_chosen_ai_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='report_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='report_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='report_task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
