# Generated by Django 5.1.7 on 2026-04-29 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_analysis', '0008_healthprofile_report_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='examining_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examined_profiles', to=settings.AUTH_USER_MODEL, verbose_name='پزشک معاینه\u200cکننده'),
        ),
    ]
