# Generated by Django 5.1.7 on 2026-05-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_analysis', '0009_healthprofile_examining_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='insurance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='بیمه'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='living_province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='استان زندگی'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='محله'),
        ),
    ]
