# Generated by Django 5.1.7 on 2026-07-25 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_analysis', '0010_healthprofile_insurance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='eye_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_images', to='test_analysis.healthprofile')),
            ],
        ),
    ]
