# Generated by Django 5.1.7 on 2026-07-27 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_analysis', '0011_eyeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase1_mask', models.ImageField(blank=True, null=True, upload_to='eye_analysis/phase1_mask/')),
                ('phase1_overlay', models.ImageField(blank=True, null=True, upload_to='eye_analysis/phase1_rgb/')),
                ('phase2_mask', models.ImageField(blank=True, null=True, upload_to='eye_analysis/phase2_mask/')),
                ('phase2_overlay', models.ImageField(blank=True, null=True, upload_to='eye_analysis/phase2_rgb/')),
                ('anemia_label', models.CharField(blank=True, max_length=16)),
                ('anemia_confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eye_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='test_analysis.eyeimage')),
            ],
        ),
    ]
