# Generated by Django 5.1.7 on 2026-07-27 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_analysis', '0012_eyeanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_tests/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('report_type', models.CharField(blank=True, max_length=255)),
                ('lab_name', models.CharField(blank=True, max_length=255)),
                ('specimen', models.CharField(blank=True, max_length=255)),
                ('collected_on', models.CharField(blank=True, max_length=64)),
                ('reported_on', models.CharField(blank=True, max_length=64)),
                ('panels', models.JSONField(blank=True, default=list)),
                ('abnormal_count', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_tests', to='test_analysis.healthprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
