# Generated by Django 5.1.7 on 2026-07-28 00:29

import hashlib

from django.db import migrations, models


def _hash_field_file(f):
    h = hashlib.sha256()
    with f.open('rb') as fh:
        for chunk in iter(lambda: fh.read(65536), b''):
            h.update(chunk)
    return h.hexdigest()


def backfill_hashes(apps, schema_editor):
    """Best-effort: hash existing files so re-uploads dedupe against them too.

    A missing/unreadable file just leaves content_hash blank — never fatal.
    """
    for model_name, field in [('EyeImage', 'image'), ('MedicalTest', 'file')]:
        Model = apps.get_model('test_analysis', model_name)
        for obj in Model.objects.all().iterator():
            f = getattr(obj, field, None)
            if not f:
                continue
            try:
                obj.content_hash = _hash_field_file(f)
                obj.save(update_fields=['content_hash'])
            except Exception:
                pass


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('test_analysis', '0013_medicaltest'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeimage',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.RunPython(backfill_hashes, noop),
    ]
