# Generated by Django 5.1.7 on 2025-03-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('double_rop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dualpredictionlog',
            name='execution_time',
            field=models.IntegerField(default=0, help_text='Execution time in milliseconds'),
        ),
    ]
