# Generated by Django 5.1.7 on 2025-03-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('double_rop', '0002_dualpredictionlog_execution_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROPResultLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_eye_label', models.CharField(max_length=50)),
                ('left_eye_confidence', models.FloatField()),
                ('right_eye_label', models.CharField(max_length=50)),
                ('right_eye_confidence', models.FloatField()),
                ('z_class_label', models.CharField(max_length=50)),
                ('z_class_confidence', models.FloatField()),
                ('execution_time', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DualPredictionLog',
        ),
    ]
