# Generated by Django 5.1.7 on 2025-03-30 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('double_rop', '0003_ropresultlog_delete_dualpredictionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROPDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_eye_label', models.CharField(max_length=50)),
                ('left_eye_confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('right_eye_label', models.CharField(max_length=50)),
                ('right_eye_confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('z_class_label', models.CharField(max_length=50)),
                ('z_class_confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('processed_in_seconds', models.DecimalField(decimal_places=4, max_digits=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='ROPResultLog',
        ),
    ]
