# Generated by Django 5.1.7 on 2025-03-30 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('double_rop', '0004_ropdetectionresult_delete_ropresultlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ROPDetectionResult',
        ),
    ]
