# Generated by Django 5.1.7 on 2025-04-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('double_rop', '0005_delete_ropdetectionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('left_image', models.ImageField(blank=True, null=True, upload_to='uploads/left/')),
                ('right_image', models.ImageField(blank=True, null=True, upload_to='uploads/right/')),
                ('left_label', models.CharField(max_length=50)),
                ('left_probability', models.FloatField()),
                ('right_label', models.CharField(max_length=50)),
                ('right_probability', models.FloatField()),
                ('z_class_label', models.CharField(max_length=50)),
                ('z_class_probability', models.FloatField()),
                ('inference_time', models.FloatField(help_text='Inference duration in seconds')),
            ],
        ),
    ]
