# Generated by Django 5.1.7 on 2025-04-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('double_rop', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionresult',
            name='left_image',
        ),
        migrations.RemoveField(
            model_name='predictionresult',
            name='right_image',
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='left_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='right_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
