# Generated by Django 5.1.7 on 2025-04-02 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('double_rop', '0007_remove_predictionresult_left_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionresult',
            name='left_image_url',
        ),
        migrations.RemoveField(
            model_name='predictionresult',
            name='right_image_url',
        ),
    ]
