# Generated by Django 5.1.7 on 2025-04-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('double_rop', '0009_predictionresult_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionresult',
            name='user',
        ),
    ]
