# Generated by Django 5.1.7 on 2025-04-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('double_rop', '0011_predictionresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='left_image',
            field=models.ImageField(blank=True, null=True, upload_to='double_rop/'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='left_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='right_image',
            field=models.ImageField(blank=True, null=True, upload_to='double_rop/'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='right_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
