# Generated by Django 5.1.7 on 2025-04-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('double_rop', '0012_predictionresult_left_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='corrected_left_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='corrected_right_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='corrected_z_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
