# Generated by Django 5.1.7 on 2025-04-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('double_rop', '0013_predictionresult_corrected_left_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='classification_status',
            field=models.IntegerField(default=1),
        ),
    ]
