# Generated by Django 5.1.7 on 2026-07-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('double_rop', '0014_predictionresult_classification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='doctor_assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='doctor_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
