# Generated by Django 5.1.7 on 2025-09-25 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('specialization', models.CharField(choices=[('kidney_stone', 'Kidney Stone (Urology)'), ('heart_disease', 'Heart Disease (Cardiology)'), ('diabetes', 'Diabetes (Endocrinology)'), ('ckd', 'Chronic Kidney Disease'), ('cardiovascular', 'Cardiovascular'), ('anemia', 'Anemia (Hematology)'), ('hypertension', 'Hypertension'), ('family_counselor', 'Family Counselor')], max_length=40)),
                ('persona', models.CharField(choices=[('kind', 'Kind & Patient'), ('in_hurry', 'Efficient & To-the-point'), ('calm', 'Calm & Reassuring'), ('analytical', 'Analytical')], default='kind', max_length=20)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='doctor_avatars/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_sessions', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='doctors_marketplace.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='doctors_marketplace.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
