# Generated by Django 5.1.7 on 2025-09-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio_fa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='headline_fa',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name_fa',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization_fa',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='doctor',
            name='tags_fa',
            field=models.TextField(blank=True, default=''),
        ),
    ]
