# Generated by Django 5.1.7 on 2025-09-29 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_marketplace', '0002_doctor_bio_fa_doctor_headline_fa_doctor_name_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='system_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='DoctorKnowledge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='doctor_knowledge/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to='doctors_marketplace.doctor')),
            ],
        ),
    ]
