# Generated by Django 5.1.7 on 2025-10-03 19:13

import doctors_marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_marketplace', '0003_doctor_system_prompt_doctorknowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorknowledge',
            name='file',
            field=models.FileField(upload_to=doctors_marketplace.models.kb_upload_to),
        ),
    ]
