# Generated by Django 5.1.7 on 2026-06-23 15:56

import django.db.models.deletion
import doctors_marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_marketplace', '0004_alter_doctorknowledge_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], max_length=10)),
                ('file', models.FileField(upload_to=doctors_marketplace.models.chat_attachment_upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='doctors_marketplace.chatmessage')),
            ],
        ),
    ]
