# Generated by Django 5.1.7 on 2026-07-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_marketplace', '0005_alter_chatmessage_content_chatattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
