# Generated by Django 5.1.7 on 2026-07-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_marketplace', '0007_chatmessage_reply_to_chatmessage_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='feedback',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_quote',
            field=models.TextField(blank=True),
        ),
    ]
