# Generated by Django 5.1.7 on 2026-07-24 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_marketplace', '0008_chatmessage_feedback_chatmessage_reply_quote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='agents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('kind', models.CharField(choices=[('reminder', 'Reminder'), ('followup', 'Follow-up')], default='reminder', max_length=10)),
                ('send_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=10)),
                ('attempts', models.IntegerField(default=0)),
                ('detail', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors_marketplace.doctor')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors_marketplace.chatsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dm_scheduled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['send_at'],
                'indexes': [models.Index(fields=['status', 'send_at'], name='doctors_mar_status_221395_idx')],
            },
        ),
    ]
